// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: chirpy_red.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const upgradeToRed = `-- name: UpgradeToRed :one
UPDATE users SET is_chirpy_red = true, updated_at = NOW() WHERE id = $1 RETURNING id, is_chirpy_red
`

type UpgradeToRedRow struct {
	ID          uuid.UUID
	IsChirpyRed sql.NullBool
}

func (q *Queries) UpgradeToRed(ctx context.Context, id uuid.UUID) (UpgradeToRedRow, error) {
	row := q.db.QueryRowContext(ctx, upgradeToRed, id)
	var i UpgradeToRedRow
	err := row.Scan(&i.ID, &i.IsChirpyRed)
	return i, err
}
