// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: userpass.sql

package database

import (
	"context"
)

const pullUserPassword = `-- name: PullUserPassword :one
SELECT hashed_password FROM users WHERE email = $1
`

func (q *Queries) PullUserPassword(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, pullUserPassword, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
